# Generated by Django 5.2.9 on 2026-01-28 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(help_text='Somente números (11 dígitos).', max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(help_text='Somente números (DDD + número).', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Somente números (DDD + número).', max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('eh_protocolo_geral', models.BooleanField(default=False)),
                ('eh_arquivo_geral', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos_substituto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='protocolos.departamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do Departamento',
                'verbose_name_plural': 'Membros do Departamento',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('numero_manual', models.PositiveIntegerField()),
                ('numero_formatado', models.CharField(db_index=True, max_length=7, unique=True)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('arquivado_em', models.DateTimeField(blank=True, null=True)),
                ('arquivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_arquivados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramitacao', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10)),
                ('acao', models.CharField(choices=[('ENCAMINHADO', 'Encaminhado'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('ARQUIVADO', 'Arquivado')], max_length=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('departamento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='protocolos.departamento')),
                ('departamento_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='protocolos.departamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Movimentação do Processo',
                'verbose_name_plural': 'Movimentações do Processo',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABERTURA', 'Abertura'), ('MOVIMENTACAO', 'Movimentação')], max_length=12)),
                ('codigo_autenticacao', models.CharField(editable=False, max_length=64, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_emitidos', to=settings.AUTH_USER_MODEL)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolos.movimentacaoprocesso')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Comprovante',
                'verbose_name_plural': 'Comprovantes',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoInteressado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolos.pessoa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Interessado do Processo',
                'verbose_name_plural': 'Interessados do Processo',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='interessados',
            field=models.ManyToManyField(related_name='processos', through='protocolos.ProcessoInteressado', to='protocolos.pessoa'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='protocolos.tipoprocesso'),
        ),
        migrations.CreateModel(
            name='TramitacaoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_externo', models.CharField(max_length=150)),
                ('contato_nome', models.CharField(blank=True, max_length=120)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('contato_telefone', models.CharField(blank=True, max_length=30)),
                ('meio_envio', models.CharField(choices=[('OFICIO', 'Ofício'), ('EMAIL', 'E-mail'), ('SEI', 'SEI'), ('MALOTE', 'Malote'), ('PORTADOR', 'Portador'), ('OUTRO', 'Outro')], default='OFICIO', max_length=20)),
                ('protocolo_envio', models.CharField(blank=True, max_length=60)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_retorno_em', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando retorno'), ('RESPONDIDO', 'Respondido / Retornado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_envio', models.TextField(blank=True)),
                ('observacoes_retorno', models.TextField(blank=True)),
                ('anexo_envio', models.FileField(blank=True, upload_to='tramitacao_externa/envios/')),
                ('anexo_retorno', models.FileField(blank=True, upload_to='tramitacao_externa/retornos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_externas', to='protocolos.processo')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('nome', 'tipo'), name='uniq_departamento_nome_tipo'),
        ),
        migrations.AddConstraint(
            model_name='departamentomembro',
            constraint=models.UniqueConstraint(fields=('departamento', 'user'), name='uniq_departamento_membro'),
        ),
        migrations.AddConstraint(
            model_name='processointeressado',
            constraint=models.UniqueConstraint(fields=('processo', 'pessoa'), name='uniq_processo_interessado'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('ano', 'numero_manual'), name='uniq_processo_ano_numero_manual'),
        ),
    ]
