# Generated by Django 5.2.9 on 2025-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Armazenado somente números (DDD + número).', max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Armazenado somente números (DDD + número).', max_length=11, null=True),
        ),
    ]
