# Generated by Django 5.2.9 on 2026-01-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tramitacaoexterna',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'AGUARDANDO')), fields=('processo',), name='uniq_tramitacao_externa_aguardando_por_processo'),
        ),
    ]
