# Generated by Django 5.2.9 on 2025-12-23 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_alter_pessoa_telefone_alter_pessoa_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequência de Processo',
                'verbose_name_plural': 'Sequências de Processo',
            },
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(help_text='Somente números (11 dígitos).', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Somente números (DDD + número).', max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Somente números (DDD + número).', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('numero_sequencial', models.PositiveIntegerField()),
                ('numero_formatado', models.CharField(db_index=True, max_length=12)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='protocolos.tipoprocesso')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramitacao', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10)),
                ('acao', models.CharField(choices=[('ENCAMINHADO', 'Encaminhado'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('ARQUIVADO', 'Arquivado')], max_length=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('departamento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='protocolos.departamento')),
                ('departamento_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='protocolos.departamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABERTURA', 'Abertura'), ('MOVIMENTACAO', 'Movimentação')], max_length=12)),
                ('codigo_autenticacao', models.CharField(editable=False, max_length=64, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_emitidos', to=settings.AUTH_USER_MODEL)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolos.movimentacaoprocesso')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Comprovante',
                'verbose_name_plural': 'Comprovantes',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoInteressado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocolos.pessoa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.processo')),
            ],
            options={
                'verbose_name': 'Interessado do Processo',
                'verbose_name_plural': 'Interessados do Processo',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='interessados',
            field=models.ManyToManyField(related_name='processos', through='protocolos.ProcessoInteressado', to='protocolos.pessoa'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoprocesso',
            index=models.Index(fields=['processo', 'registrado_em'], name='protocolos__process_fbe1c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='processointeressado',
            constraint=models.UniqueConstraint(fields=('processo', 'pessoa'), name='uniq_processo_interessado'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('ano', 'numero_sequencial'), name='uniq_processo_ano_numero'),
        ),
    ]
