# Generated by Django 5.2.9 on 2026-01-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_tramitacaoexterna_uniq_tramitacao_externa_aguardando_por_processo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tramitacaoexterna',
            name='uniq_tramitacao_externa_aguardando_por_processo',
        ),
    ]
