# Generated by Django 5.2.9 on 2025-12-23 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_sequenciaprocesso_alter_pessoa_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoprocesso',
            options={'ordering': ['-registrado_em'], 'verbose_name': 'Movimentação do Processo', 'verbose_name_plural': 'Movimentações do Processo'},
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoprocesso',
            name='protocolos__process_fbe1c3_idx',
        ),
        migrations.AlterField(
            model_name='movimentacaoprocesso',
            name='registrado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
