# Generated by Django 5.2.9 on 2026-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_remove_tramitacaoexterna_uniq_tramitacao_externa_aguardando_por_processo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TramitacaoExterna',
        ),
    ]
