# Generated by Django 5.2.9 on 2026-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0004_delete_tramitacaoexterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoprocesso',
            name='acao',
            field=models.CharField(choices=[('ENCAMINHADO', 'Encaminhado'), ('RECEBIDO', 'Recebido'), ('DEVOLVIDO', 'Devolvido'), ('ARQUIVADO', 'Arquivado'), ('RECEBIDO_EXTERNO', 'Recebido Externo')], max_length=20),
        ),
    ]
