# Generated by Django 5.2.9 on 2026-01-30 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0005_alter_movimentacaoprocesso_acao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='responsavel_setor',
            field=models.ForeignKey(blank=True, help_text='Servidor responsável pelo processo dentro do setor atual (para setores com múltiplos membros).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
